# Generated by Django 4.2.3 on 2023-09-13 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0002_alter_comentario_pessoa'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comentario',
            table='tb_comentarios',
        ),
    ]
